# Generated by Django 4.0.3 on 2022-05-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='tempo_duracao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
